baseURL = 'https://example.org/'

locale = 'de-DE'
defaultContentLanguage='de'

theme = 'ananke'

title = 'Tischtennis SGS Erlangen'
description="Tischtennis in der Sportgemeinschaft Siemens e.V."

[params]
    site_logo = "images/SGS_Logo_100_100.svg"
    featured_image_class = "cover bg-center"

[menus]

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"                   # points to content/_index.md
    weight = 5

