baseURL = 'https://example.org/'

locale = 'de-DE'
defaultContentLanguage='de'

theme = 'ananke'

title = 'Tischtennis SGS Erlangen'
description="Tischtennis in der Sportgemeinschaft Siemens e.V."

[params]
    site_logo = "images/SGS_Logo_100_100.svg"
    featured_image_class = "cover bg-center"
    header_section_class = "tc-l pv3 ph3 ph4-ns" # make the header (site-header i.e home page and list pages) smaller

[menus]

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"                   # link to content/_index.md
    weight = 5

[[menu.main]]
    identifier = "training"
    name = "Training"
    url = "/training/"          # link to content/training/_index.md
    weight = 10
    
[[menu.main]]
    identifier = "aktuelles"
    name = "Aktuelles"
    url = "/aktuelles/"          # link to content/aktuelles/_index.md
    weight = 20
    